sudo: true
os: trusty
cache: false
notifications:
  email:
    recipients:
    - v.strajt@gmail.com
    - xstrv30@vse.cz
    on_success: always  
    on_failure: always
env:
- URL=https://developer.salesforce.com/media/salesforce-cli/sfdx-linux-amd64.tar.xz
before_install:
#Assign variables
- export SFDX_AUTOUPDATE_DISABLE=false
- export SFDX_USE_GENERIC_UNIX_KEYCHAIN=true
- export SFDX_DOMAIN_RETRY=300
- export SFDX_DISABLE_APP_HUB=true
- export SFDX_LOG_LEVEL=DEBUG
- mkdir sfdx
- wget -qO- $URL | tar xJ -C sfdx --strip-components 1
- "./sfdx/install"
- export PATH=./sfdx/$(pwd):$PATH
- dir
- sfdx --version
- sfdx plugins --core
- sfdx force:auth:jwt:grant --clientid $CONSUMERKEY --jwtkeyfile assets/server.key
  --username $USERNAME --setdefaultdevhubusername -a HubOrg
script:
- sfdx force:org:display -u HubOrg
- sfdx force:source:deploy -u HubOrg -p force-app/main
- sfdx force:mdapi:deploy -d destroy -w 1
- sfdx force:apex:test:run -u HubOrg --wait 10 --codecoverage --resultformat human
